# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: url shortener

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: ["opened", "synchronize"]

env:
  # verbosity setting for Terraform logs
  TF_LOG: INFO
  # Credentials for deployment to AWS
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  # S3 bucket for the Terraform state
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.53

    - name: Build
      run: go build -v ./...

  terraform:
    runs-on: ubuntu-latest
    #map a step output to a job output
    outputs:
      health_endpoint: ${{ steps.save.outputs.url }}
    defaults:
      run:
        shell: bash
        # We keep Terraform files in the terraform directory.
        working-directory: ./terraform
    steps:
      - name: Checkout the repository to the runner
        id: terraform
        uses: actions/checkout@v2

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
            terraform_wrapper: false
            terraform_version: 1.3.0
      - name: Terraform init
        id: init
        run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve -input=false

      - name: save public ip
        id: save
        run: echo "url=http://$(terraform output -raw public_ip):8080/health" >> "$GITHUB_OUTPUT"

      - name: check URL
        run: echo $url

      - name: check URL2
        run: echo ${{ steps.save.outputs.health_endpoint }}

  health_check:
    needs: terraform
    runs-on: ubuntu-latest
    steps:

      - name: check url 1
        env:
          URL: ${{needs.terraform.outputs.health_endpoint}}
        run: echo $URL

      - name: check url 2
        env:
          URL: ${{needs.terraform.outputs.health_endpoint}}
        run: echo ${{ env.URL }}

      - name: Check the deployed service URL
        env:
          URL: ${{needs.terraform.outputs.health_endpoint}}
        if: github.event_name == 'push'
        uses: jtalk/url-health-check-action@v3
        with:
          # Check the following URLs one by one sequentially
          url: ${{ env.URL }}
          max-attempts: 60 # Optional, defaults to 1
          # Delay between retries
          retry-delay: 5s # Optional, only applicable to max-attempts > 1
          # Retry all errors, including 404. This option might trigger curl upgrade.